language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
script:
  - python setup.py install
  - nosetests -vv --with-cov --cov-config .coveragerc --cov-report term-missing
after_success:
  - coveralls
